name: End-to-End Tests
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v1
      - name: Run tests
        uses: DevExpress/testcafe-action@latest
      - name: Run a one-line script
        run: echo Hello, world!  
          
